# Generated by Django 5.2.4 on 2025-08-19 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='published_articles',
            field=models.ManyToManyField(blank=True, related_name='independent_authors', to='news_app.article'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='published_newsletters',
            field=models.ManyToManyField(blank=True, related_name='independent_newsletters', to='news_app.newsletter'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor')], default='reader', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
